-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 21:30:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sspmi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sspmi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sspmi` DEFAULT CHARACTER SET utf8 ;
USE `sspmi` ;

-- -----------------------------------------------------
-- Table `sspmi`.`secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspmi`.`secretaria` (
  `idsecretaria` INT NOT NULL AUTO_INCREMENT,
  `nomenclatura` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `whatsapp` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idsecretaria`),
  UNIQUE INDEX `idsecretaria_UNIQUE` (`idsecretaria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sspmi`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspmi`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `secretaria_idsecretaria` INT NOT NULL,
  `nomenclatura` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `whatsapp` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`iddepartamento`, `secretaria_idsecretaria`),
  UNIQUE INDEX `iddepartamento_UNIQUE` (`iddepartamento` ASC),
  INDEX `fk_departamento_secretaria1_idx` (`secretaria_idsecretaria` ASC),
  CONSTRAINT `fk_departamento_secretaria1`
    FOREIGN KEY (`secretaria_idsecretaria`)
    REFERENCES `sspmi`.`secretaria` (`idsecretaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sspmi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspmi`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `departamento_iddepartamento` INT NOT NULL,
  `departamento_secretaria_idsecretaria` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(200) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `imagem` VARCHAR(45) NOT NULL DEFAULT 'default.jpg',
  `situacao` TINYINT NOT NULL DEFAULT 0,
  `telefone` VARCHAR(11) NULL,
  `whatsapp` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusuario`, `departamento_iddepartamento`, `departamento_secretaria_idsecretaria`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuario_departamento1_idx` (`departamento_iddepartamento` ASC, `departamento_secretaria_idsecretaria` ASC),
  CONSTRAINT `fk_usuario_departamento1`
    FOREIGN KEY (`departamento_iddepartamento` , `departamento_secretaria_idsecretaria`)
    REFERENCES `sspmi`.`departamento` (`iddepartamento` , `secretaria_idsecretaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sspmi`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspmi`.`historico` (
  `idhistorico` INT NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT NOT NULL,
  `pagina` VARCHAR(45) NOT NULL,
  `acao` VARCHAR(45) NOT NULL,
  `campo` VARCHAR(100) NOT NULL,
  `valorAtual` VARCHAR(100) NOT NULL,
  `valorAnterior` VARCHAR(100) NULL,
  `dataHora` TIMESTAMP NOT NULL,
  `ip` VARCHAR(12) NOT NULL,
  `navegador` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idhistorico`, `usuario_idusuario`),
  UNIQUE INDEX `idhistorico_UNIQUE` (`idhistorico` ASC),
  INDEX `fk_historico_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_historico_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `sspmi`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
